### ISSUE TITLE
Let's Go Safari issues

### ISSUE THREAD

**Issue by MaabusArcade** [teknogods/TeknoParrotUI#1000]
The exe that TPUI shows for Lets Go Safari is wrong. It currently has GameTestR_RingWide.exe as the needed exe. It should be GameSampR_Ringwide.exe. 
The lgs.xml file in UserProfile is incorrect. This line <ExecutableName>GameTestR_RingWide.exe</ExecutableName> near the very bottom should be <ExecutableName>GameSampR_RingWide.exe</ExecutableName>

Also when toggling the test menu the game crashes, but the test menu will work. If you launch the game with GameTestR_RingWide.exe it will boot into the test menu. When you toggle the test menu it says it is loading GameSampR_Ringwide with the -t argument. 

Steering does not work, but i believe this is a known issue. But you can at least load the game and let it aimlessly go through the stage.

**Comment by Boomslangnz** [comment]
Hello, these issues are now all fixed. Thanks
