### ISSUE TITLE
Bombergirl arcade

### ISSUE THREAD

**Issue by Haile1969** [teknogods/TeknoParrotUI#1006]
Saw someone asking for bombergirl arcade support 
on the livestream yesterday so reaver fyi it doesn’t work with spice 
it works as is but without full saving ain’t worth much that’s why it needs tp support 
besides since when does it matter if a game works with the alternatives?you answered yourself so what? to someone mentioning night hunter already working i’ll add bombergirl has even a discord for it and its very popular and lots of users waiting for it to be supported by tp also as a tp subscriber its disappointing for me that you guys still skip support for it

**Comment by jcstahl1** [comment]
https://www.mayoclinic.org/diseases-conditions/schizophrenia/symptoms-causes/syc-20354443#:~:text=Overview,aren't%20observed%20by%20others.

**Comment by Haile1969** [comment]
Lol
you obviously very bored jcstahl1 but if you as a subscriber decided not to ask for anything at least be 🤫 and don’t interfere me or others for asking for more games to be supported as a tp subscribers
