### ISSUE TITLE
wangan 6RR support

### ISSUE THREAD

**Issue by Haile1969** [teknogods/TeknoParrotUI#1007]
As a tp subscriber i’m still waiting for wangan 6RR version 3.05 tp support with saving 
why support the previous old ones and skip support for it?
also i same as many other users find it very disappointing that wan6 server still offline
despite it was promised by you guys to bring it back online long ago

**Comment by AngryScotsmanGaming** [comment]
They have your money now bud they don't care!

**Comment by Haile1969** [comment]
I care and many others that pay and that’s what matters.
i’m waiting for a very long time for bombergirl arcade+wangan 6RR version 3.05
tp support and still nothing!

**Comment by AngryScotsmanGaming** [comment]
Read what I said and evaluate it?

**Comment by Haile1969** [comment]
As i wrote i don’t mind paying so pocky and other devs that work hard will
get paid for it but i do want them to listen to requests instead of ignore/delete posts.
