### ISSUE TITLE
Street Fighter 3rd Strike needs hide mouse toggle please

### ISSUE THREAD

**Issue by OndaCouch421** [teknogods/TeknoParrotUI#1013]
when u get time can u please add that or to the games that need it ill make a big post at some point of the issues that i find so i dont make duplicated threads. thanks again

**Comment by Haile1969** [comment]
There are a few that needs hide mouse cursor if you have time check all games 
and post the full list.
should help for future fix.

**Comment by Poliwrath** [comment]
Hello, I have reported both of your accounts to Github for constant malicious spam attacks, good day.
