### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Play3rBust3r** [teknogods/TeknoParrotUI#162]
I'm trying to make it past the main menu of hotd4, but no buttons work. I tried disabling my touchpad, removing the eeprom and the config file but it doesn't work. Any idea?

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report :)

**Comment by Harmmmm** [comment]
Should be fixed in current version, feel free to create a new ticket if you still have problems.
