### ISSUE TITLE
PoV

### ISSUE THREAD

**Issue by phibryzo** [teknogods/TeknoParrotUI#192]
Hello,
I use Qanba PCB for play on my cab. Up, Down, left and right are points of view. No analogic system. So, in fighting climax, when I do this combinaison : "down, down+left and left, my character stay down (with left). No tested with other "Pad" Game.
I don't want emulate a xinput or other xpadder for preserve ressources (little config).

Thank you !

**Comment by AiTeknoparrot** [comment]
I can confirm the issue of DirectInput POV inputs not working correctly also occurs in Melty Blood RingWide, Melty Blood RingEdge2, Fighting Climax Ignition, Persona 4 Arena, and all the other TeknoParrot-compatible 2D fighting games. Essentially it is impossible to input any directional specials (hadouken, shoryuken, etc.) with POV directions using a game pad or basic arcade stick controller.

**Comment by Boomslangnz** [comment]
Thanks for bug report guys, Just pushed fix :)

**Comment by phibryzo** [comment]
Thank you for your work ! I test !

**Comment by phibryzo** [comment]
Good Job ! Work Perfectly
