### ISSUE TITLE
Lets go island 3d and Lets go island mouse problem

### ISSUE THREAD

**Issue by EmuAl** [teknogods/TeknoParrotUI#213]
the game gun cursor is stuck to the top of the screen, in windowed and FS... if you push the mouse cursor till its near the top of the screen then the game gun cursor comes through the bottom of the screen and into the game then works properly also in windowed mode the screen starts way down the bottom right of the desktop.

![2020-05-03 (5)](https://user-images.githubusercontent.com/47227078/80937777-6e357d00-8dce-11ea-9f0f-907956bfafdc.png)

![2020-05-03 (7)](https://user-images.githubusercontent.com/47227078/80937745-53fb9f00-8dce-11ea-994d-3e5ee6a91976.png)

**Comment by GtrevizeG** [comment]
I can confirm having the same issue. Win 10 latest update Nvidia Card. 4k screen if needed.

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report :)

**Comment by EmuAl** [comment]
yes is working much better now, the mouse works as intended covering the whole area of the screen on both LGI games.

For me, in windowed mode the game still starts way down the bottom right of the desktop, like in the second picture, now the game screen is grabbing the mouse so you can't just move it back up, you have to alt tab to a different window then move it up to see the game window, after you move it, the mouse again works as it meant to covering the whole screen.

A small problem still exists with window mode but overall much better and thanks for fixing the mouse stuff.

**Comment by Harmmmm** [comment]
Good to hear aiming issues are fixed.
Windows being a dick and spawning the window at a random inconvenient position is not a TP issue.. ;)

**Comment by Nezarn** [comment]
@EmuAl try on latest TP, should be fixed now (for games that are starting in bottom right corner like LGI, LGI3D, ID6-8, etc.)
