### ISSUE TITLE
Brake not mapped in MK DX

### ISSUE THREAD

**Issue by Aethyrion** [teknogods/TeknoParrotUI#233]
TeknoParrot 1.0.0.140:
- Assign any Xinput axis or button to Brake in TPUI controller setup.
- The issue can be confirmed in the Test Menu : all other mapped inputs are properly registered, the brake is not.

The issue isn't present in old TeknoParrot 1.92: the Brake work properly with any XInput axis.

**Comment by Nezarn** [comment]
Use proper profile, not MKDX USA
