### ISSUE TITLE
Media write protected ?

### ISSUE THREAD

**Issue by phibryzo** [teknogods/TeknoParrotUI#245]
Hello,

I've a issue with my new arcade conf :
- Media write protected.

I use ISO file to contain RE game. Also, Teknoparrot write files in game folder. I want to preserve proper dump. Can you change this PLS ?

[exception.txt](https://github.com/teknogods/TeknoParrotUI/files/5542283/exception.txt)

**Comment by nzgamer41** [comment]
ISO files are read only, you need to extract the game from the image. Closing this.
