### ISSUE TITLE
Mayflash Dolphinbar Not Recognized as 2 Seperate Inputs for 2 Player Lightguns in Raw Input Mode

### ISSUE THREAD

**Issue by xocruncheyriceox** [teknogods/TeknoParrotUI#254]
Teknoparrot 1.0.0.498 is recognizing both dolphinbars as mayflash dolphinbar 8. 

The buttons both map properly to each individual controller but only 1 wiimote/(controller) is driving the cursor on the game.

**Comment by Harmmmm** [comment]
It's fixed in latest update! Feel free to open another ticket if you still have problems.
