### ISSUE TITLE
Teknoparrot encountered an exception and crashes

### ISSUE THREAD

**Issue by jfree427** [teknogods/TeknoParrotUI#343]
TP crashes when I hit the escape key to exit for some games.
 Screen shot below and log attached.

![image](https://user-images.githubusercontent.com/22616973/182940016-986560ce-9924-4e77-92c7-46bf67317eab.png)
[exception.txt](https://github.com/teknogods/TeknoParrotUI/files/9262839/exception.txt)

**Comment by Headrush69** [comment]
I'm having this issue lately as well but the error window closes so fast I can't capture.

I don't know if the case is the same for you jfree427 but I only get this error when starting TP from a command prompt. If I start TP first no error on game exit. So it appears related to TP's exit.

**Comment by EmiMidnight** [comment]
fixed with TPUI version 1.0.0.1054
