### ISSUE TITLE
Amdaemon.exe error while trying to play sega alls game

### ISSUE THREAD

**Issue by Arthurfogo7** [teknogods/TeknoParrotUI#359]
![20230113_230226](https://user-images.githubusercontent.com/85951083/212488064-8988d5d8-f6cc-4fe3-8362-b7859726f43f.jpg)
How can I solve this? I saw on some chinese forum that it had something to do with directx, but I'm not sure about this, so I need some to help me.

**Comment by nzgamer41** [comment]
Which game are you trying? Does TeknoParrot show any errors, or is it just amdaemon?

**Comment by Arthurfogo7** [comment]
Teknoparrot just opens and closes, doesn't do anything. When I opened the game folder Amdaemon has this log. Nothing more. House of the Dead: Scarlet Dawn

**Comment by Nezarn** [comment]
Closing because of false report, pictured amdaemon folder is from a (publicly) unsupported game
