### ISSUE TITLE
KOF Skystage runs too fast 

### ISSUE THREAD

**Issue by Arcadeguy781** [teknogods/TeknoParrotUI#367]
As the title states, when I play this game, regardless of the region, it runs way too fast.

**Comment by Arcadeguy781** [comment]
Found a fix. I lowered my FPS on my NVIDIA control panel to 60 fps. Since it’s only a fix for NVIDIA I’m not going to close it

**Comment by Nezarn** [comment]
> Found a fix. I lowered my FPS on my NVIDIA control panel to 60 fps. Since it’s only a fix for NVIDIA I’m not going to close it

99% of arcade games are made for 60 fps (60hz vsync). (and I'm closing this since it was user error, failing to limit fps to 60)
