### ISSUE TITLE
House of the dead Ex Not Opening

### ISSUE THREAD

**Issue by MarioluigiFan2009** [teknogods/TeknoParrotUI#374]
Today I downloaded House of the dead EX Then I set it up But then Once it starts launching it just Closes I try every method but nothing works.Is there any way to fix it? (I don't know if it was The elfLdr2 Because it worked for Aliens Armageddon not that and Sorry if it had a little bit of typo).

**Comment by Arcadeguy781** [comment]
You have to move two files over to the elfdr2 folder, and those are the SO files, so you want to go to the House of the Dead EX folder, go to disk0, elf, and move both .SO files and the .bak file

**Comment by MarioluigiFan2009** [comment]
!!it worked Thank you so much!!

**Comment by MarioluigiFan2009** [comment]
Nope! it crashed on the very first mini game.

**Comment by MarioluigiFan2009** [comment]
Nope! it crashed on the very first mini game.

**Comment by MarioluigiFan2009** [comment]
I mean it worked for windowed But when I try fullscreen It crashes on the first Minigame.

**Comment by MarioluigiFan2009** [comment]
I mean it worked for the windowed But when I try full screen It crashes on the first mini game.
