### ISSUE TITLE
Outrun 2 SP - Lines 

### ISSUE THREAD

**Issue by Riddler1** [teknogods/TeknoParrotUI#378]
Hi Team....

Many people have asked why there are graphic lines on the Demo screen and above the rev counter when racing...

i think it is caused by the "Bilinear Filter" option on teknoparrot.

Do you know who implemented this feature?

by turning it off (which i don't think anyone wants to do, or has done) it fixes the problem.....

Before....
![Screenshot_20230303-111754_Video Player.jpg](https://user-images.githubusercontent.com/43607359/222713412-d86d9cc3-e8fd-4211-8dab-c1c209107c70.jpg)

After...
![Screenshot_20230303-113957_Video Player.jpg](https://user-images.githubusercontent.com/43607359/222713509-ef6f143e-7537-477f-b899-b5329837b255.jpg)

rev counter before...
![Screenshot_20230303-114305_Gallery.jpg](https://user-images.githubusercontent.com/43607359/222713588-8d07a41c-c148-4a75-bc63-47ad53fae3e0.jpg)

rev counter after...
![Screenshot_20230303-114249_Gallery.jpg](https://user-images.githubusercontent.com/43607359/222713646-5eb9b90d-3f94-4b5e-9b7b-c7c1a24433ba.jpg)

Hopefully now this is known, it can be worked on. 

All the best guys

**Comment by Nezarn** [comment]
Its an option because some people wanted non-pixellated HUD textures in 69k resolution.

Don't want artifacts\pixellated textures? Play the game in the original 800x480 resolution (and don't use the option to force filtering)
