### ISSUE TITLE
Player/getData - Judgement/getData

### ISSUE THREAD

**Issue by olivier33590** [teknogods/TeknoParrotUI#389]
Hello,
I can't interpret the player and judgment backup IP frames:

MKDX retrieves data in the format: (for player info, but there is also Judgement)
[0,["",0,0,"",0,1677677875,"10.22","Nickname",92,2,0,0,4,0,3,0,-1,68,2,23 ,2,41,2,4,21,81,48,348,0,6,9,1],[[[16,2,0,0,0],[12,2,0,0,0], [11,2,0,0,0],[0,2,0,0,0],[3,2,0,0,0]],[[0,2,0,0,0], [14,2,0,0,0],[4,2,0,0,0]],[[18,2,2],[41,2,2],[56,2,2], [68,2,2],[23,2,2],[100,1,0],[57,1,0]]],[],[[0,0,0,0,0,6 , 0.0], [0.0.1,0,6.0.0]], "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]

and send the backup to update the profile registers, in the form:
[1676705217,"1234",1677677875,"10.22",["",0.0,"",0,"Nickname",92,2,0,0,4,0,3,0,-1.68 ,2,23,2,41,2,4,21,81,48,348,0,6,9,1,"JPN"],[[],[],[[57,1]],1,1 0,0,1],"110"]

Could you give me some indications to understand and interpret the data as the teknoparrot.com site does in the MKDX player profile

My project is to finalize a profile server for MKDX for Chinese arcade cabinets, delivered under teknoparrot, without active banapassport.
I managed to develop my server allowing the passing player to flash a QRcode to activate his profile before activating the banapassport command on the game. But it currently only works with a teknoparrot ID in the profile parameters ( repeater mode to telnoparrot.com).

Players passing through for a few days will not create a profile on this system plus a profile on teknoparrot, return to the local profile to indicate the teknoparrot ID to finally play. For these passing players, I need to be able to make a local backup like the teknoparrot service does. But I can't quite figure out the dataframes to format them and store them in the database.

Thanking you for helping me

**Comment by Nezarn** [comment]
We don't support bootlegging.

**Comment by olivier33590** [comment]
Sorry, the terminal is delivered like this, it is not us who do it. We don't sell, we just use.
I take care of these two terminals in a vacation center, and some big players will seek the possibility of saving, starting with the center staff. This is the reason why I looked into the question being a developer too.

Now my solution is working in some form but I'm going to spend a few sleepless nights with oldg and figure out how the data storage and transmission works in order to update my data tables properly with or without you.

**Comment by Poliwrath** [comment]
great, nothing is stopping you. less freeloading off of the work of others so your paying customers are happy :)
