### ISSUE TITLE
The new update caused Wanga 5 not to work today

### ISSUE THREAD

**Issue by bluejaye** [teknogods/TeknoParrotUI#392]
Hi Team

The new update caused Wanga 5 not to work today. After showing the game, it reported an Unkown error E0001.
Please review

Regards.

**Comment by Boomslangnz** [comment]
Hello, this is incorrect. Just tested and working perfectly fine. Issue is your end and not latest update

Good luck

**Comment by bluejaye** [comment]
Thank you for the reply.

in this case, it must be my NVIDIA driver issue.  that's the only thing I updated last night.

**Comment by bluejaye** [comment]
I re-installed the NVIDIA drive  (Clean install) and it fixed the issue.

Thanks
