### ISSUE TITLE
the house of the dead ex controls not working

### ISSUE THREAD

**Issue by juan200213** [teknogods/TeknoParrotUI#400]
hello

in the video game the house of the dead ex, the controns dont work, I can't press start or shoot, please fix it thanks.

**Comment by fire0128** [comment]
This works perfectly, the issue might be your system

**Comment by juan200213** [comment]
So how do I get the controls to work?

**Comment by juan200213** [comment]
Hello I put the file libsegaapi.so.bak in elfloader2 folder to get the controls of house of the dead ex working but teknoparrot suddenly delete the file, please fix it
