### ISSUE TITLE
Virtual Fighter ESports APM3 Doesn't start

### ISSUE THREAD

**Issue by EmuAl** [teknogods/TeknoParrotUI#414]
After the game starts you get the press any button screen, you press the button to get to the play with aime or play as guest screen.
the input doesn't work on this screen and the game won't start no matter which button you press on any of the available options.
have tried a clean install of both game and TP, 
have tried removing user profile and setting game up again.
Quite a few people have same issue.

**Comment by EmuAl** [comment]
looks like blade strangers suffers the same problem, no button starts the game

**Comment by EmuAl** [comment]
so vfesports is now fixed thanks for that :)
but blade strangers starts then after that you have to delete the 2 save.bins that are created in the game folder in order for the game to start again. This needs to be done each time in order to play the game again.

**Comment by EmiMidnight** [comment]
blade strangers was fixed in early may so this can be closed i think
