### ISSUE TITLE
Not lunching because of Error

### ISSUE THREAD

**Issue by FoxieZack** [teknogods/TeknoParrotUI#416]
Does anyone have any fixes for this error? Im not sure how to fix it.

![Screenshot 2023-04-03 132844](https://user-images.githubusercontent.com/72839443/229621292-7b24ab33-75a7-4586-862a-aae74088cd81.png)

**Comment by ReaverTeknoGods** [comment]
c:\Users\ZACK\Documents\My Music

Move TeknoParrot to c:\teknoparrot or c:\games\teknoparrot or similar folder.
