### ISSUE TITLE
In Showdown Issues

### ISSUE THREAD

**Issue by unionjac** [teknogods/TeknoParrotUI#421]
Thanx to Boom for this amazing games Issues are if u step on brakes it brings up pause menu sometimes. Also main issue is if you play tours after 1st race controls die so you need to restart the game can't continue. No test menu in Tp can't go to options menu no key assigned  also cant find manual pause no key assigned
Thanks

**Comment by unionjac13** [comment]
everything fixed as I asked and everybody else did. Just wondering if you could add  the test menu and maybe the options menu thank you

**Comment by unionjac13** [comment]
that game is sega showdown thx

**Comment by Boomslangnz** [comment]
you can modify all options via ini files, but we may add support for test menu soon
