### ISSUE TITLE
My 10 games with Issues.  Need assistance for fixes.

### ISSUE THREAD

**Issue by therafcave** [teknogods/TeknoParrotUI#422]
1- Daytona 3 won't load

2-Justice league won't play full screen

3-Mario Kart DX FFB effects are very few and little effect

4-Operation Ghost plays top half screen only

5-Outrun 2 won't load

6-Raiden III and IV plays horizontal not vertical.

7-Rampage plays choppy

8-R-Tuned Ultimate Street Racing won't load

9-Transformers won't load

10-The Fast and Furious supercars won't load

Thanks for any help.

**Comment by Nezarn** [comment]
1,5,7,8,9,10 - they work fine, read this -> https://teknogods.github.io/getstarted.html (if they still don't work, get a new dump from your real cabinets)
2 - if your monitor doesn't support the required resolution, it won't work obviously
4 - same as above
3 - FFB is fine
6 - https://www.youtube.com/watch?v=9jr_p25DzLM
