### ISSUE TITLE
Having issues launching TeknoParrotUi

### ISSUE THREAD

**Issue by initiald415** [teknogods/TeknoParrotUI#455]
Here is a copy of what pops up when I run as admin
![TeknoError](https://github.com/teknogods/TeknoParrotUI/assets/5104861/5b9b8fa8-5225-4b52-82db-ebc054890897)

**Comment by Nezarn** [comment]
Try putting TPUI\games to non-windows folders. (like C:\TP or D:\Games\TP or something like that, don't use documents\desktop\program files)
