### ISSUE TITLE
Game Launch Issues

### ISSUE THREAD

**Issue by CHILEYMAN213** [teknogods/TeknoParrotUI#457]
I've re-extracted it a hundred times where it says I installed it too much wait hour and try again and turned off antivirus and still nothing this is what I get :

"Cannot find.\OpenParrotWin32\OpenParrotLoader. exe!"
"it's probably removed by your anti-virus software."
"Please re-extract TeknoParrot."

can someone please help I'm loosing my mind trying to figure this out LMMFAO!!!!!!!!!! thank you to any who can help

**Comment by nzgamer41** [comment]
Follow the instructions
