### ISSUE TITLE
Exception happened during loading ParrotData.xml Generate new one by saving ! (when launch the teknoparrot)

### ISSUE THREAD

**Issue by Speedyboys** [teknogods/TeknoParrotUI#472]
I already had this problem 1 month also tried everything all method like install c++ and DirectX, move into D:\ and more but still not luck i will show you a pic hope you get the solution:)
![image](https://github.com/teknogods/TeknoParrotUI/assets/137507534/a3d2cb43-6ac8-4d0d-98ea-6301ac1a4a97)

**Comment by Speedyboys** [comment]
If i dont respond quick or many days please dont close it because i really need this problem to remove thanks :)

**Comment by EmiMidnight** [comment]
Have you tried deleting ParrotData.xml in your TPUI folder? (next to the teknoparrot exe) Something about it must have gotten corrupted. If you delete it, it will generate a new clean one.

**Comment by Speedyboys** [comment]
> Have you tried deleting ParrotData.xml in your TPUI folder? (next to the teknoparrot exe) Something about it must have gotten corrupted. If you delete it, it will generate a new clean one.

Owh ok i will try that sorry for late respon
