### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by 20031035** [teknogods/TeknoParrotUI#486]
![ta](https://github.com/teknogods/TeknoParrotUI/assets/140726998/75136d01-8d87-42ae-aabb-ed830c6bb036)
[exception.txt](https://github.com/teknogods/TeknoParrotUI/files/12184400/exception.txt)

**Comment by EmiMidnight** [comment]
Needs more information. What folder and drive do you have the game and TP installed to?
The error means it cannot access the file, put them somewhere your normal windows user account has permissions too.

**Comment by EmiMidnight** [comment]
Closed due to inactivity and too little info
