### ISSUE TITLE
Resolution settings fo Sonic Dash Extreme

### ISSUE THREAD

**Issue by GaussTek** [teknogods/TeknoParrotUI#541]
Hello!

No matter what offset I set for this game (default is 26), I can't get it to work, the game shows up as extremely big at the left of the screen, doesn't matter if you select Full Screen or Windowed.

I was wondering if it would be possible to add resolution options like with Mario & Sonic Rio, which work perfectly.

This is how it looks with the default offset. Tried messing with many but none seem to work.

![2023-09-17 11_30_50-SonicDash _ Release_Ring](https://github.com/teknogods/TeknoParrotUI/assets/43524067/b12d0bb5-2c36-42ee-bbf8-babd875dc854)

Thanks a bunch for all the hard work

**Comment by EmiMidnight** [comment]
Hey there, can you try it with the latest update? TPUI should have some custom resolution settings for you now.

**Comment by GaussTek** [comment]
> Hey there, can you try it with the latest update? TPUI should have some custom resolution settings for you now.

OMG, yes thank youuu! Now the game works as intended!! Tried multiple resolutions in windowed mode and they work fine, just like Mario & Sonic Rio.

Thanks a lot for your time doing this, you are amazing!!
