### ISSUE TITLE
Hummer Extreme Edition loads with screen partially cropped.

### ISSUE THREAD

**Issue by zestful** [teknogods/TeknoParrotUI#556]
Hummer Extreme Edition loads with screen partially cropped.

Testing in both full screen and windowed mode

![image](https://github.com/teknogods/TeknoParrotUI/assets/12581227/aeb55cd2-29a2-40b9-93bf-477e61193b4b)

Windows 10, Intel CPU, NVDIA 2060 Super

**Comment by EmiMidnight** [comment]
Can you update and try with the new version I just pushed? Should fix it. Lemme know if it works.

**Comment by zestful** [comment]
Still seeing the same issue after applying the update

**Comment by Boxdgm** [comment]
I was having this same issue but it was caused by one of the text files having the game configured to 2560x1440 instead of 1080p which is my monitors resolution. Once I adjusted the text file it was normal and no longer cropped.

**Comment by zestful** [comment]
Yeah that's the resolution it's setting itself to, struggling to find a config file that sets it though, will let you know if I ever do

**Comment by KIRBY2-0** [comment]
i know the config fille and where it is, XF86Config, but i do not know how to use it.

**Comment by zestful** [comment]
Thanks boxdgm, found the file and change my resolution to 1920x1080 all working great now!

File location can be found in:  disk0\data-hummer\config\kernel.nut

**Comment by zestful** [comment]
I'll leave this open and see if Teknoparrot devs can make this a game settings option, so others don't run into this problem, but if they disagree that's fine too as it can be fixed via this file

**Comment by EmiMidnight** [comment]
A bit late but added, resolution can be set via TPUI now. :)
Gonna close this for now.
