### ISSUE TITLE
Wangan Midnight MT 3

### ISSUE THREAD

**Issue by scooby911** [teknogods/TeknoParrotUI#563]
This is no more possible to calibrate a wheel (in dinput and xinput modes). On the I/O calibrate menu of the game, after pressing test, there is a PCB error and it is not possible to exit of this menu.
When the game was added, everything was right. The problem occurs after the addition and some changes on the MT 3DX version.

**Comment by Boomslangnz** [comment]
yeah known issue unfortunately without current fix

 for now change the testmode.lua (in game folder\env\tmp\data) manually

CalibrationSteering = 32768

**Comment by EmiMidnight** [comment]
Fixed in todays update.
