### ISSUE TITLE
TP UI update error

### ISSUE THREAD

**Issue by cangarujack** [teknogods/TeknoParrotUI#609]
Hi, 
someone can fix this error during last update?
![Senza titolo-1](https://github.com/teknogods/TeknoParrotUI/assets/103336398/847243b0-b0a5-4af8-9494-30c7d672ddf0)

**Comment by rudeboy03** [comment]
Also having a similar/same issue 
![Screenshot 2023-12-25 083037](https://github.com/teknogods/TeknoParrotUI/assets/154814404/fb50f8f8-a5e2-4149-9663-5ee3a708421e)

**Comment by Boomslangnz** [comment]
Yes there was an issue if you were on a specific version which prevents being able to update correctly, please download latest TeknoParrot UI update manually which resolves this going forward 

https://github.com/teknogods/TeknoParrotUI/releases
