### ISSUE TITLE
TP UI update error message

### ISSUE THREAD

**Issue by rudeboy03** [teknogods/TeknoParrotUI#610]

**Comment by rudeboy03** [comment]
Attempting to update TP and keep getting this error message 
![Screenshot 2023-12-25 083037](https://github.com/teknogods/TeknoParrotUI/assets/154814404/f7727aee-61cf-47a2-bbf3-f207bc7df177)

**Comment by Boomslangnz** [comment]
Yes there was an issue if you were on a specific version which prevents being able to update correctly, please download latest TeknoParrot UI update manually and copy to TeknoParrot folder which resolves this going forward 

https://github.com/teknogods/TeknoParrotUI/releases
