### ISSUE TITLE
Hummer Extreme Ai fix

### ISSUE THREAD

**Issue by Dankfambo25** [teknogods/TeknoParrotUI#613]
Ai is way too fast and tested with tp 1164, i did also tried to change the hz of my monitor to 60 and still the ai goes really fast, any fix?

**Comment by EmiMidnight** [comment]
Hummer is a 30hz game and anything faster will break the AI

**Comment by Dankfambo25** [comment]
> Hummer is a 30hz game and anything faster will break the AI

thanks for the heads up

**Comment by Dankfambo25** [comment]
> Hummer is a 30hz game and anything faster will break the AI

hey emi it worked for a moment but when i happen to try again the ai seems to keep going fast and i limit to 30hz

**Comment by EmiMidnight** [comment]
I saw you reopened it with another question but it's gone now so I don't know if you fixed it or not, but just in case you didn't:
Check kernel.nut in the data-hummer/config folder with a text editor and make sure FRAME_COUNT is set to 30. If you set that to 60 then the game still does math based on 60fps even with 30fps lock, I think.

**Comment by Dankfambo25** [comment]
> I saw you reopened it with another question but it's gone now so I don't know if you fixed it or not, but just in case you didn't: Check kernel.nut in the data-hummer/config folder with a text editor and make sure FRAME_COUNT is set to 30. If you set that to 60 then the game still does math based on 60fps even with 30fps lock, I think.

emi you're a life saver thank you, also sorry i did delete the comment and close it as i was trying to find the issue and i didn't want to annoy you, but that was the issue and it seems to work regardless of my refresh rate of my monitor

**Comment by EmiMidnight** [comment]
That's what Github Issues are for though so don't worry! I might add it to the wiki in a bit. :)

**Comment by mooock** [comment]
the issue could also be seen in attract mode. the AI just drives into the wall if set to 60
