### ISSUE TITLE
Hummer mouse cursor not hiding

### ISSUE THREAD

**Issue by ScapeGoat43** [teknogods/TeknoParrotUI#619]
with tp 1170 hummer boots with mouse cursor hidden set to on and vanished only after moving the mouse during boot

**Comment by EmiMidnight** [comment]
Fixed in the last few updates. Closing. :)

**Comment by vikings630** [comment]
I am now getting an error 1011 calibration setting not set correctly when loading up the game. I just played it yesterday and loaded no problems. I did not update it or anything. any ideas??
