### ISSUE TITLE
Initial D 7 shader error (AMD fix)

### ISSUE THREAD

**Issue by Riddler1** [teknogods/TeknoParrotUI#621]
Hi team 

following the recent AMD fixes (24th Dec) for initialD games, when loading InitialD 7 it shows this error...
![20231228_204104](https://github.com/teknogods/TeknoParrotUI/assets/43607359/a1eb8caf-8abd-4646-8834-d1af825fbeae)

this error happens when the "gpu fix" option is set as AMD, New AMD, or Intel

when setting the option to "None", the game loads but gives green screens....
![20231228_204455](https://github.com/teknogods/TeknoParrotUI/assets/43607359/615c01f2-6541-40fc-91e9-117fa3a17ab7)

![20231228_204616](https://github.com/teknogods/TeknoParrotUI/assets/43607359/e9752952-b561-4645-ba34-653ce0f00c8a)

I loaded InitialD 8 to test and it still works ok. i dont know what other initialD games might be affected

Was last working on 1.0.0.1142 (Dec 15th)

PC Specs:
Windows 10 pro
AMD A10 7890k cpu
Nvidia GT1030 gpu (GDDR5)
16GB DDR3 ram 1600MHz

**Comment by Riddler1** [comment]
testing....

1) un-installed Nvidia driver 546.29 and installed updated to latest version 546.33

2) updated teknoparrot to version 1.0.0.1179

still shows error and green screens as described above

there is an "err.cg" file being created in the initial D7 rom folder root. 

![20240101_234426](https://github.com/teknogods/TeknoParrotUI/assets/43607359/6a4e3ee1-7dd6-4bd0-8f66-e3ddfb974297)

is this a graphics card issue or teknoparrot?  any help would be great.

**Comment by Riddler1** [comment]
testing....
3) updated visual c++ 2015-2022 x64 to version 14.38.33130

4) updated visual c++ 2015-2022 x86 to version 14.38.33130

no change 😥

**Comment by nzgamer41** [comment]
AMD fix is for AMD graphics card not AMD CPU. You don't need the AMD fix since you have NVIDIA GPU and need to re-extract your game as the files will be modified for AMD GPU now.
