### ISSUE TITLE
Regression: The House of the Dead EX crashes on startup

### ISSUE THREAD

**Issue by antoniodesousa** [teknogods/TeknoParrotUI#625]
The House of the Dead EX used to work for me not so long ago. But now it crashes immediately after booting the game.  And I haven't changed any of the files in months. So, it has to be a bug introduced in TP not so long ago.

![2023-12-30_19-41-08 mkv_30_12_2023_19_45_48](https://github.com/teknogods/TeknoParrotUI/assets/10920974/1d46a3fb-f495-4b5b-83ab-83703aab5b8e)

**Comment by Nezarn** [comment]
What are your game settings? using windowed? fullscreen?
I can't reproduce this issue.

**Comment by Cheesmaker** [comment]
same thing appens to me with lindbergh game in the real lindberg arcade cab and the original LCD wich is 59hz (with Virtua Fighter 5)... Just and Edid pb for me I've got to setup a special resolution with 1360x768 60hz. You can use CRU to look at your edid specifications.

**Comment by antoniodesousa** [comment]
![hotdex](https://github.com/teknogods/TeknoParrotUI/assets/10920974/1cce831c-f69d-4240-ba9f-41432b19c86d)

@Nezarn I tried all different display modes: Windowed, Fullscreen and Windowed Fullscreen.
In discord > patreon-help, there're another 2 users with the same error Frogman and razors78.
And the issue doesn't seem to be AMD specific, because razors78 has a Nvidia GPU.
And like I said before, the game used to work fine.

@Cheesmaker I already have a custom resolution with 1360x768 60hz setup in Adrenalin.

**Comment by razors78** [comment]
True that. The game crashes quickly back to TP UI no matter what display settings are set. Used to work fine before. No changes made to any game files. I use Nvidia GPU. Must be a bug introduced in one of the later updates, most likely an issue with the elfloader. Hopefully this can be resolved! Thanks!

**Comment by Nezarn** [comment]
Seems like an update wiped any non-bundled libs in lib folder, pls copy librnalindbergh_jr.so libcri_soundoutput_lindbergh_jr.so and it will work again.
