### ISSUE TITLE
The House of the Dead EX Crashes After Mission Select

### ISSUE THREAD

**Issue by Yardl3y** [teknogods/TeknoParrotUI#630]
I'm fully updated on the latest version of TP and now The House of the Dead EX is crashing after selecting a mission. I already tried copying librnalindbergh_jr.so and libcri_soundoutput_lindbergh_jr.so over to ElfLdr2/libs even though they were still there after the update. My game settings are set to Japan and display mode is set to FullScreen Windowed, I have also tried Fullscreen.

**Comment by antoniodesousa** [comment]
I can confirm the same happens to me. After selecting a mission, the game immediately closes. Also, the cutscenes don't render anything besides some text. I don't know if it's only specific to AMD GPUs. I don't have a Nvidia GPU to test it out.

**Comment by Yardl3y** [comment]
> I can confirm the same happens to me. After selecting a mission, the game immediately closes. Also, the cutscenes don't render anything besides some text. I don't know if it's only specific to AMD GPUs. I don't have a Nvidia GPU to test it out.

I’m using Nvidia. I can see the cut scenes after selecting a Madison but a few seconds into the cut scenes is when the game crashes.

**Comment by razors78** [comment]
Same here. Game crashes back to TP UI after selecting level. Used to work fine way back in time. I'm on Nvidia.

**Comment by slothbeatr** [comment]
Just tested, same here. no cutscenes, only text, crashes on either mission select. AMD gpu as well.

**Comment by poskass** [comment]
The same thing happens to me with Nvidia, the game comes out at the end of cut scenes

**Comment by primereed** [comment]
Upon mission select, game crashes.  Using Nvidia

**Comment by Ltort79** [comment]
Some here. Amd GPU. No fullscreen, crash after mission select. Copied file. So in elfldr lib

**Comment by steven44** [comment]
Same here as well. I am using I7 6700K CPU, rtx2060 card and 32g of ddr4 ram. After selecting a level the game just crashes back to the Ui. Correct 2 files are placed in ElfLdr2 folder. Thank you.

**Comment by peter634** [comment]
just tested with tp 1184
same here the game crashes to desktop 
after the stage selection 
any fix?
T.Y

**Comment by peter634** [comment]
fixed👍
only the mouse cursor still visible 
even if marked

**Comment by antoniodesousa** [comment]
The mouse cursor not hiding is unrelated to this ticket. You should close this ticket and open a new one for the cursor. But as far as I can remember that option never worked before.

**Comment by peter634** [comment]
it did 
and its related to the subject 
so i don’t see no point of opening a new
ticket for the mouse cursor not hiding 
as for closing the ticket that’s yardl3y to decide he opened it

**Comment by Yardl3y** [comment]
This issue has been resolved with the latest update. The game no longer crashes.

**Comment by Yardl3y** [comment]
This issue has been resolved with the latest update. The game no longer crashes.
