### ISSUE TITLE
"No Updates Found" Message on Launch despite "Check for Updates on Launch" being disabled

### ISSUE THREAD

**Issue by Pete-McDonald** [teknogods/TeknoParrotUI#643]
Hey Team,

Hope you're good, love the project - of course :)

This is a really, really minor thing - but I've noticed that if you disable "Check for Updates on Launch" and save - when you launch TP it still shows the message "No Updates Found".

I've attached screenshots below - again super minor and not important, but wanted to raise it :)

Thanks again for all your amazing work.

![1](https://github.com/teknogods/TeknoParrotUI/assets/82280111/c72b8ea1-6e0b-4da9-8d02-881a71fe0a48)

**Comment by EmiMidnight** [comment]
This should hopefully be fixed in a few minutes. It seems there was a leftover check from when we had to fix the updater a bit when we switched the descriptions folder to metadata instead.

**Comment by peter634** [comment]
auto updates don’t work anymore with tp 1186
even if marked
manually it works
waiting for a fix
T.Y

**Comment by Pete-McDonald** [comment]
> auto updates don’t work anymore with tp 1186 even if marked manually it works waiting for a fix T.Y

You'll want to raise your own issue for this, peter.  This thread is specifically about the "No Updates Found" message

**Comment by Pete-McDonald** [comment]
> This should hopefully be fixed in a few minutes. It seems there was a leftover check from when we had to fix the updater a bit when we switched the descriptions folder to metadata instead.

Thanks so much for the quick fix Emi, just tested it and confirmed it's all sorted :)
