### ISSUE TITLE
Wheel of Fortune and Deal or No Deal not launching in Teknoparrot

### ISSUE THREAD

**Issue by Lastfaceullevac** [teknogods/TeknoParrotUI#647]
Every time I try to launch both of these games they both crash on "detecting Linux game" Does anyone know how to fix this?

**Comment by nanometrovovo2** [comment]
I have the same issue with Deal or No Deal. Even I can see a new window flash but returns to TP. I have tried with v1.17 and 1.18. Both seems to load but crash to TP.
Wheel of Fortune runs ok for me but I'm interested in TP support for v1.20 that includes other languajes.

**Comment by Boomslangnz** [comment]
Hi, this should be fixed now. Thanks
