### ISSUE TITLE
auto updates

### ISSUE THREAD

**Issue by peter634** [teknogods/TeknoParrotUI#648]
auto updates don’t work anymore with tp 1186
even if marked
manually it works
waiting for a fix
T.Y

**Comment by antoniodesousa** [comment]
Same here with TP 1.0.0.1186

**Comment by EmiMidnight** [comment]
Fixed in a few minutes with the next update, sorry

**Comment by antoniodesousa** [comment]
I just tested and it's fixed! 👍

**Comment by peter634** [comment]
fixed👍
