### ISSUE TITLE
Gaelco Pc Based Slow audio

### ISSUE THREAD

**Issue by TheCoolPup** [teknogods/TeknoParrotUI#657]
Gaelco Tuning Race, Ring Riders, and Tokyo Cop all have slower audio tempo than original hardware. https://youtu.be/jKZLULaeuls?feature=shared This video is running on tekno. https://youtu.be/gZ_GhS4XPU4?feature=shared This video is on a real cabinet. Can confirm the same bug exists in the other two games.

**Comment by EmiMidnight** [comment]
Should be fixed now

**Comment by TheCoolPup** [comment]
THANK YOU

**Comment by TheCoolPup** [comment]
actually seems ring riders still has the same issue

**Comment by TheCoolPup** [comment]
what im thinking whatever you did with tokyo cop could be done with ring riders and gaelco tuning race

**Comment by TheCoolPup** [comment]
scratch that, tuning race doesnt have that issue

**Comment by EmiMidnight** [comment]
Tuning Race should have been fixed yesterday with the original update.
Ring Riders should be fixed in a few minutes, didn't realize I had to manually update the dll for elfldr2 games.

**Comment by TheCoolPup** [comment]
issue is fixed now, thank you emi :)
