### ISSUE TITLE
gashaaaan crosshair not aligned

### ISSUE THREAD

**Issue by sem1992** [teknogods/TeknoParrotUI#675]
Why the ticket for it got deleted?
the crosshairs still not aligned with 
the shooting for gashaaaan
just tested with tp 1197+core 1113
waiting for a fix
thanks

**Comment by razors78** [comment]
I'm wondering too. Ticket got deleted as well for this issue.  it still hasn't been fixed. So please have another look at it and make sure it works soon. Thanks!

**Comment by Nezarn** [comment]
@sem1992 
Because you don't take 
your skizo meds 
spamming here and on discord in DMs 
whenever  a dev has open DMs 24/7
waiting for you to take your meds
and stop spamming
thanks

**Comment by Poliwrath** [comment]
The tickets get closed due to spam, this is the same user who has been spamming our discord, patreon, github for the past two years.
