### ISSUE TITLE
gashaaaan+virtua fighter 5R

### ISSUE THREAD

**Issue by sem1992** [teknogods/TeknoParrotUI#676]
virtua fighter 5R last matches(2-6)+gashaaaan aiming not fixed
so when you guys don't have answers you either call it a "spam" or just delete posts or trying lame insults
you should learn to respect users that pay you every month
fix stuff and add new games support people ask for
keep telling yourself the same lies 
when the truth is completely different
that's all

**Comment by razors78** [comment]
True that, and I couldn't agree more with the statement above. It's spot on!
