### ISSUE TITLE
Crusin Blast 

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#699]
Intel Processors boot no issue Amd Ryzen not booting

**Comment by legend800** [comment]
We have some users with Intel reporting unreliable boot. It's definetely a race condition to get the rendering going. Once it starts, the game is fine other than the title music not stopping when the race begins. 

<img width="885" alt="2024-02-26 18_29_44-Discord _ #teknoparrot _ TeknoGods — Mozilla Firefox" src="https://github.com/teknogods/TeknoParrotUI/assets/20983844/23e0b045-2f78-46cc-a969-06585d1ba35d">

**Comment by brewernerd** [comment]
Adding some data points:
PC1, win 10 Intel 9900k 3060ti, nvidia driver 531.68 starts everytime
PC2, win 10 AMD 2600 1080ti nvidia driver 546.33 starts 1/20+ times
PC3, win 10 Intel 8700k 2060 nvidia driver 546.33, started never so far...10+ attempts

**Comment by Dutchman2000** [comment]
Game runs fine for me in windowed or 1920x1080 full screen resolution.  It crashes when I try to use my laptop's native resolution, 2560x1600 in full screen.  Intel i7 with Nvidia 4070. This game needs the custom resolution switch I think.

**Comment by PeeJayBonobo** [comment]
Took a lot of tinkering, but when it works, it runs at 120fps....

Ryzen 9 5900X @4.625GHz and Radeon RX 6800, btw.
