### ISSUE TITLE
Ghost Squad Evolution

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#715]
Many of us would love to play this shooter but it has never worked .Maybe if you devs have the time could we revisit this and get it working properly on all systems. All subs would really appreciate it.

THANKS

**Comment by Hydreigon223** [comment]
As of right now, GSE was promoted out of subscriber mode without evident QA. I posted a detailed version of the problem in Teknogods issue branch here: https://github.com/teknogods/teknoparrot-issues/issues/246

**Comment by Hydreigon223** [comment]
This input problem is now resolved as of 1.0.0.1295.
