### ISSUE TITLE
Sonic dash missing coin input.

### ISSUE THREAD

**Issue by revnmaynard** [teknogods/TeknoParrotUI#722]
There’s no free play option in test menu and no coin input in the controller setup either. Impossible to start a game. It load’s excellently. Hope you guys can find away to implement this. Thanks

**Comment by LordsOfTheRealm** [comment]
it's a ticket game...set what ever button to start......research is your best learner...

**Comment by revnmaynard** [comment]
> it's a ticket game...set what ever button to start in the tp games controller settings.....research is your best learner...

Start button has been set to multiple different inputs with the same results . In test menu I’ve set it to amusement  from tickets. In my research in the discord search all I’ve found is others asking the same about six months ago without any resolution.

**Comment by revnmaynard** [comment]
So I guess the service button is the coin button hopes this helps someone else
