### ISSUE TITLE
Cruis'n Blast will not start on latest version of TP

### ISSUE THREAD

**Issue by westhillsgetaway** [teknogods/TeknoParrotUI#728]
Hi, I cannot get CB 1.25 to run at all. It launched upon first try, and then no success after that. I am on latest build of TP (1.0.0.1238). I have fresh dump copy. CPU: i5-3470, GPU: GTX1650 Windows 11

I receive error message [ERROR.LOG]: Received FATAL signal SIGSEGV (11).

Others in Discord have reported the same error a month ago, but have gone quiet so I'm assuming their issue was resolved; not sure what else to try. Deleted pmuser folder, deleted the game from TPUI and re-added, re-installed, rebooted, tried custom resolution, no changes in behavior. I've attached a screenshot if it helps at all.

![Screenshot_20240330_211129_Gallery](https://github.com/teknogods/TeknoParrotUI/assets/128206171/892056ac-40f7-4f83-bd44-a90a5b9f71a2)

**Comment by murdle** [comment]
Hi, do you found a solution ? i can't launch this game and all game of patreon ...

**Comment by westhillsgetaway** [comment]
I ended up installing a fresh/brand new copy of TP in a different location on my hard drive and it resolved the problem. I then moved the clean install back to my original location on the hard drive and it still worked. So it was something with my existing install but a clean install fixed it. I backed up my UserProfiles folder and copied it over to my new install in order to retain my game settings/controller binds. Hope this helps.

**Comment by murdle** [comment]
Thank you, i go for try that.

**Comment by murdle** [comment]
it's good for me, thank you bro

**Comment by KRIS85oO** [comment]
> I ended up installing a fresh/brand new copy of TP in a different location on my hard drive and it resolved the problem. I then moved the clean install back to my original location on the hard drive and it still worked. So it was something with my existing install but a clean install fixed it. I backed up my UserProfiles folder and copied it over to my new install in order to retain my game settings/controller binds. Hope this helps.

For me not working :\
