### ISSUE TITLE
Theatrhythm Final Fantasy ASC currently you are unable to set the buttons for this game

### ISSUE THREAD

**Issue by Soulphraser** [teknogods/TeknoParrotUI#729]
On a previous version you were able to set the buttons to play this game now you are no longer able to.

**Comment by LordsOfTheRealm** [comment]
did you set it up to play using the mouse first to select . then in game the controls work that you set up...

**Comment by Soulphraser** [comment]
thanks I actually got it set up properly now honestly it was just all user error
