### ISSUE TITLE
Samurai Shodown

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#736]
This game loads and goes back to desktop not sure what the issue is several people having same issue maybe thier is a trick to it. thought the devs could maybe take a quick look  thanks as always 
unionjac1313
 i am using it on an 11th gen i7 intel with 64 gigs ram and 3060ti

**Comment by Pete-McDonald** [comment]
Confirmed fixed after Emi's patch in latest TP update
