### ISSUE TITLE
Got 3 Red on virus total scan

### ISSUE THREAD

**Issue by ych5470** [teknogods/TeknoParrotUI#743]
just download it today, Apr.26.2024, 
upload to virustotal, 

got three **RED**, 
could we ignore them or ?

Bkav Pro:     W32.AIDetectMalware.CS
MaxSecure:    Trojan.Malware.300983.susgen
Trapmine:    Suspicious.low.ml.score

Thanks

**Comment by Nezarn** [comment]
If you downloaded it from our [website](https://teknoparrot.com/) or our github its false positive.

**Comment by ych5470** [comment]
OK, got it, 
yes, I downloaded it from here, 
will ignore it. 

Thanks for the answering..
