### ISSUE TITLE
Sonic Dash Extreme crash at boot since one of the last TeknoParrot updates

### ISSUE THREAD

**Issue by PolybiusExtreme** [teknogods/TeknoParrotUI#746]
Sonic Dash Extreme crash at boot since one of the last TeknoParrot updates. I tried it with a fresh and clean TeknoParrot setup and it crash at boot. The game works with old versions of TeknoParrot.

**Comment by antoniodesousa** [comment]
I can confirm that the game does indeed crash in the latest TP 1.0.0.1250 release.

**Comment by Nezarn** [comment]
@PolybiusExtreme Do you use RTSS?

**Comment by PolybiusExtreme** [comment]
@Nezarn No i don't use RTSS or any other tool. Just a fresh and clean TeknoParrot setup. I have an old version of TeknoParrot also without any tools like RTSS and with this old version it works.

**Comment by PolybiusExtreme** [comment]
@EmiMidnight Thanks it works! :)
