### ISSUE TITLE
Wrong game executables for After Burner Climax and Wacky Races

### ISSUE THREAD

**Issue by PolybiusExtreme** [teknogods/TeknoParrotUI#757]
After Burner Climax:
abc_1080p is not the correct game executable because it is patched. Please add abc to the game executables.
Wacky Races:
Launcher.exe is not the correct name of the game executable. The correct name is game.exe. Please add it too to the game executables.

**Comment by EllimistArcade** [comment]
Wacky Races Launcher.exe is correct
![image](https://github.com/teknogods/TeknoParrotUI/assets/118787798/5ce08abc-cb0d-4dbc-845d-cf28634853d3)

There is no game.exe in Wacky Races dump
![image](https://github.com/teknogods/TeknoParrotUI/assets/118787798/fed3a240-f437-4811-8428-d2d05018a4b2)

What is difference with patched game executable? It comes with every dump you can find (along with regular abc). Can update but any real reason to if patched does the same things but better/fixed?

**Comment by PolybiusExtreme** [comment]
The exe in the Wacky Races dump is renamed (no clean dumps available). Every other Taito game executable is named game.exe.

The same with After Burner Climax. There is no official HD game executable so it is not a clean dump. The HD patched executable have graphical issues (the HUD is not correctly showed). The correct and official executable is abc.

**Comment by EllimistArcade** [comment]
Ill let TP team weigh in on Wacky Races. If there is no game.exe in any dump then it doesnt make sense to put it. The goal of this is to help people get the game running, not confuse them with an exe that doesnt exist in any dump. If every dump uses Launcher.exe to launch thats the game exe as far as anyone wanting to play the game is concerned. 

Will update After Burner Climax for the abc though to abc_1080

**Comment by PolybiusExtreme** [comment]
Can you just make it that game.exe and Launcher.exe is available to set and abc and abc_1080?

**Comment by EmiMidnight** [comment]
Will probably check if we can add specifying multiple possible executables, but in the meantime even if the UI by defaults limits to a special name, you can just change it in the windows file picker to be able to pick whichever file you want:

![TeknoParrotUI_(Running)_-_Microsoft_Visual_Studio_2024-05-11_03-19-39](https://github.com/teknogods/TeknoParrotUI/assets/4989638/990163fa-3f94-4563-aca0-201b74f64c22)
