### ISSUE TITLE
BUG BUSTERS

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#759]
Bug Busters works with intel gfx cards built in but no function with nvidia 3080ti no boot black screen please help.

thx unionjac1313

**Comment by magicray1028** [comment]
I was also unable to boot using Nvidia RTX 4060 with D3d8.dll

**Comment by 00C0FFEE** [comment]
game is old 640 x 480, dont intend to play it ultra4k.
please close
