### ISSUE TITLE
Daemon Bride Additional Gain not visible in "Add Game"

### ISSUE THREAD

**Issue by Pete-McDonald** [teknogods/TeknoParrotUI#763]
Hey team,

Daemon Bride Additional Gain doesn't seem to appear in TPUI.  I've updated, and I can see the "DaemonBrideAG.xml" in the UserProfiles folder, but it doesn't appear in the UI.  I've captured a screenshot of the UI after just attempting an update to show it's all up-do date.  

Any thoughts? :)

![image](https://github.com/teknogods/TeknoParrotUI/assets/82280111/cc046856-44da-4ad6-8f96-1af920558f74)

![image](https://github.com/teknogods/TeknoParrotUI/assets/82280111/c49bf26c-3022-4767-a1ca-0a868bf68760)

**Comment by EmiMidnight** [comment]
It should not be in userprofiles unless you had it added to your library before, so there's something weird going on there. Did you manually mess around with this profile before? Try deleting the one in UserProfiles so it regenerates it from GameProfiles instead.

**Comment by Pete-McDonald** [comment]
Thanks for the quick response @EmiMidnight.  I do apologise, I think you're right that way back in time I was trying to get this to load in TP on my own.

Deleting that xml from UserProfiles made it appear in the "Add Library" function, it's definitely a Pete thing!  Thanks again for your help and sorry for the hassle!

**Comment by EmiMidnight** [comment]
Np, glad it works now!
