### ISSUE TITLE
TARGET TERROR GOLD

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#766]
Just was playing this game with friends and noticed some key things maybe pocky or coffee may wanna look only if you have time i know you are busy .well the issues I have noticed are an unusual wait time before the live feed, and the reporters audio only works in the first stage. I do not think this is correct. was tested on all i7 10-11th gen 3060ti nvidias thx for input

unionjac13

**Comment by Edward47385** [comment]
got the same issues 
its about a min long of wait with live feed message 
before the missions starts and the audio of the reporter 
only work on first stage pick(any stage)when completed and picking a new one 
there's no audio for her

**Comment by YOBoys81** [comment]
Same issue here. Hoping for a fix

**Comment by benjc** [comment]
I had the game running great then noticed the delay start to happen after a graphics driver update. Reverting to an older version of the driver software fixed it so that might be worth a try until TP can sort this?

**Comment by EmiMidnight** [comment]
Closed as it should be fixed now
