### ISSUE TITLE
police trainer 2

### ISSUE THREAD

**Issue by Edward47385** [teknogods/TeknoParrotUI#767]
the game isn't fully playable 
at the stage of the sergeant with red coins 
only 1100 points max can be achieved 
when the minimum if failed a few times are 1400
making it impossible to complete 
also half robots visible at last patrolman swat stage

**Comment by Nezarn** [comment]
Can you stop spamming rrz? Take your skizo meds, your reports are always ignored, and whenever you spam either here on github or on discord, it makes people want to work on those specific things less because you're annoying as fuck.

Also game is playable, just play in original resolution.
