### ISSUE TITLE
Police trainer 2 : Original res option removed ?

### ISSUE THREAD

**Issue by nixxou** [teknogods/TeknoParrotUI#769]
Why this option was removed ? It was not working ?

Without that we get flying robots : 
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/0e60d162-f7e5-4f07-bdd0-4f2ace8049b2)

**Comment by Nezarn** [comment]
It was working, but people didn't want to use the original resolution, and also complained when they broke it by stretching to 69k resolution. It won't be added back.
