### ISSUE TITLE
Police trainer 2 resolution issues

### ISSUE THREAD

**Issue by magicray1028** [teknogods/TeknoParrotUI#770]
Police trainer shooting aim is still offset in 4:3 mode. Changing light gun to 4:3 mode works as a fix but would be awesome if native resolution can correct it. Current resolution also causes patrolman swat stage-half robots visible.And sergeant red coins stage to be impassable due to missing coins.

**Comment by Nezarn** [comment]
Play the game in the original resolution. (if you start spamming because your friend RRZ asked you (just like on discord before), you will get banned too)
