### ISSUE TITLE
responce to poliwrath about closing ticket 789👆

### ISSUE THREAD

**Issue by wade473** [teknogods/TeknoParrotUI#790]
1.never had a youtube account or twitter so don’t lie
2.asking for fixes or more public games support isn’t “spamming”
its a fairytale invented by you guys
3.when you close/ignore a confirmed issue with the lame excuse of
“denied support” and not fix it you ain’t punishing me 
you punishing ALL USERS that can’t play a broken game
also 
instead of using unjustifiable ban or blocking/delete posts why not answer a legitimate questions?
how about answering:thank you for reporting an issue/asking 
we’ll try get it fixed/supported
here’s some questions you guys avoid answering 
because when it was posted on discord the post got deleted very fast:
1.when will you add public support for transformers shadows rising that you have?
2.anyone working on terminal emu for exvs2+xboost?
people that got one pc without vpn CAN’T PLAY both
3.are the trackball games bowl o rama,puck off,golf still worked on?
4.what happened to virtue fighting 5 cards saving support that was promised?
5.why aren’t you bringing back the online server for wangan 6 as before?
6.what’s the progress on ghost squad evo+king of the road?
7.wangan 6RR,Initial d the arcade,bombergirl girl arcade,silent scope bone eater,chase chase jokers,the swarm,superR speed,gunslinger stratos 3
all those games are public,decrypted and available for months now!
anyone even works on adding support for them?
8.any plans to add support for the public fgo version 9.61?
9.can you add online/offline saving for jojo?
the solo play against bots or users is disabled currently

**Comment by nzgamer41** [comment]
https://www.helpguide.org/articles/mental-disorders/helping-someone-with-schizophrenia.htm
