### ISSUE TITLE
Outrun 2 requiring subscription when not labeled on add game with (Subscription)

### ISSUE THREAD

**Issue by carltheraveyt** [teknogods/TeknoParrotUI#800]
For some reason Outrun 2 SDX isn't labeled on Add Game as (Subscription) , I tried to launch it with the game path filled in and the CMD window that comes up checks for subscription.  this needs amending on the list to show as subscription.

**Comment by cor094** [comment]
The game is properly labeled, it does not require a subscription. The CMD window does check subscriber status, but the game will load either way. Try unchecking the score submission stuff in game settings if checked.

**Comment by carltheraveyt** [comment]
i've got the score submission unchecked and still doesn't launch see pics 
![Screenshot 2024-06-27 020053](https://github.com/teknogods/TeknoParrotUI/assets/22319140/3d6d1d34-7ff9-4910-888b-34ed3ccb258d)
![Screenshot 2024-06-27 020122](https://github.com/teknogods/TeknoParrotUI/assets/22319140/fbc8b525-2bde-4a6d-ab44-9dd754665f02)

**Comment by cor094** [comment]
Score - Enable Submission is checked in your screenshot. You can also try a different resolution in case your monitor doesn't suppoet the 800x480 that's currently set

**Comment by cor094** [comment]
But your most likely issue is game executable is set to the force feedback plugin
