### ISSUE TITLE
Wheel sensitivity after last update

### ISSUE THREAD

**Issue by aletondaX** [teknogods/TeknoParrotUI#804]
After the 2024-07-01 update performed by TeknoParrot, it seems to me that steering sensitivity became way higher than usual.

I think it affects all racing games in my library. Some games i tested were Daytona, Outrun and R-Tuned.

I can tell it's not just my feeling, because i play Daytona 1 and 2 too, in their respective emulators, and they seem to run as usual.

Edit: wheel name is Eurocase EUGA-80 MARANELLO

**Comment by Boomslangnz** [comment]
Hi,

No one has touched anything that would affect direct input axis sensitivity in any capacity. Could you try fresh TeknoParrotUI install and see if same issue occurs. Double check wheel software too to ensure wheel rotation is set correctly

**Comment by aletondaX** [comment]
Thanks for the response!

Good to hear the devs didn't touch anything related to dinput, i guess it's a problem on my end then. I'm gonna reinstall TP, recalibrate and double check everything.
