### ISSUE TITLE
Game Error (E0001)

### ISSUE THREAD

**Issue by Louis7542** [teknogods/TeknoParrotUI#812]
I have tried both Wangan Midnight Maximum Tune 6/6R, but this error still occurs. Is there any way to solve it? Thanks I currently use a MacBook Pro M1 Max and use wineskin to simulate 64-bit execution of emulators and games.
<img width="1351" alt="5e52e4b3f570299aeb240554e9e1497a" src="https://github.com/teknogods/TeknoParrotUI/assets/97740640/0b9153eb-5965-475c-8b2f-9748d4dfc124">

**Comment by nzgamer41** [comment]
This will be because macOS isn't supported using WINE. You might have more luck trying Windows using something like UTM or Parallels, otherwise you'll need a Intel based machine that can run regular amd64 Windows
