### ISSUE TITLE
Storm Racer G slow load when started minimized

### ISSUE THREAD

**Issue by trundeg** [teknogods/TeknoParrotUI#813]
Dear Tekno team,

There is an issue with Storm Racer G, when it is started from the command line with the minimized option, the game is very slow to load. This problem is very unique to this game, I never experienced it even if I always use the minimized option.

Here is the command line:
`TeknoParrotUi.exe --profile=SRG.xml --startMinimized`

Best regards

**Comment by nzgamer41** [comment]
So the game runs fine and loads normal speed if launched through the UI normally? It's only if launched from the command line it runs slow?

**Comment by trundeg** [comment]
Yes, when launched from the command line AND with the option --startMinimized.

**Comment by trundeg** [comment]
Hi there. I tested again today and it seems te bug has been fixed now. Thanks for your help !
