### ISSUE TITLE
the act missing graphics

### ISSUE THREAD

**Issue by yoshi200214** [teknogods/TeknoParrotUI#819]
in the video game there some missing graphics like the lives, the play now clapperboard and the protagonist sprite in the chase scene,
please fix it because this graphics are missing since the game was added two years ago

**Comment by kaddisemu** [comment]
Can confirm, there is supposed to be a lives counter as well as a "play now" clapperboard sprite indicating when you are supposed to do something

**Comment by kaddisemu** [comment]
For example:
https://youtu.be/ndR3onVaRh8?si=lwbmK4fK9FMjyW-C

**Comment by EmiMidnight** [comment]
Should be fixed with the latest elfldr2 update.
