### ISSUE TITLE
target terror gold little audio issues

### ISSUE THREAD

**Issue by yoshi200214** [teknogods/TeknoParrotUI#820]
hello
in target terror gold there some issues with the audio for example theres to little audio delay noticle in the raw news cinematic and in the scene of the women reportes theres supossed to be a breaking news song
heres the comparison
emulator: 
https://youtu.be/U9NHElY26k8?si=X6Vpt5BZieAR4CPV
real hardware:
https://youtu.be/LKUk_1bDFQ8?si=Up_255w5MF2brMjY

**Comment by Boomslangnz** [comment]
Hi, yeah i noticed about the audio delay but it appears to happen on real hardware too

https://www.youtube.com/watch?v=A44ZRElG5g8&t=499s

i have just pushed a fix for the missing breaking news song etc

**Comment by Boomslangnz** [comment]
I took another look and just pushed fix for audio delay issue

Thanks for bug report
