### ISSUE TITLE
A bug in the debug menu of wmmt3(Export)

### ISSUE THREAD

**Issue by dgndzxgndxg** [teknogods/TeknoParrotUI#825]
Hello! thx very much for your works on wmmt3! I love the game so much. However there is a small problem in the debug menu of the game. 

I was about to make a debug card in the menu and I tapped the test button (or gas pedal) to enter the player name and select the player car. However the game crashed and didnot respond. I wonder whether there would be a fix to this bug.

P.S. attached is the way to enter that menu:
launch the game>test button>debug>himamura>create debug card>name enter or car select

*in the inner debug menu,use gearbox 3,4 to move the cursor and use the gas pedal or test button as the enter

**Comment by derole1** [comment]
Just want to add onto this, believe this isnt an issue with ElfLdr. Have tested this on real hw, trying to enter a name causes a seg fault.

**Comment by dgndzxgndxg** [comment]
Got it.Now i can edit the card file using your cardtool. thx :) 
Btw do you know how to create a card with MAX HP and MAX Handling? Seems that sb has made it but I cant find more info

**Comment by derole1** [comment]
> Got it.Now i can edit the card file using your cardtool. thx :) 
> Btw do you know how to create a card with MAX HP and MAX Handling? Seems that sb has made it but I cant find more info

Under data2 increase tune point and adjust power/handling as needed.

This has stayed from a TP issue now so I'd suggest closing this and raising any issues with the card editor in the respective repository.
