### ISSUE TITLE
Caladrius AC shows white screen and doesn’t load

### ISSUE THREAD

**Issue by romadu** [teknogods/TeknoParrotUI#839]
Caladrius AC launches to a white screen and doesn’t show the game. I have Nvidia card but the issue appears with nvidia discreet and intel integrated gpu.

**Comment by enodr** [comment]
Same here, Nvidia GPU. Works with Ring Loader but with Teknoparrot white screen and "this app is not responding" behavior

**Comment by Ennahh-76** [comment]
Same here, intel i5 with Nvidia card

**Comment by Bad-A-Billy** [comment]
Same here still w/Nvidia...

**Comment by Bad-A-Billy** [comment]
Fixed in todays build. Thx!
Is this working for others also so this can be closed?

**Comment by lesurfeur** [comment]
I confirm for my part as well. Works now, no more white screen. Thanks to the DEV.
Intel(R) Core(TM) i7-6700HQ / GeForce GTX 960
W10-64b 22H2

**Comment by Ennahh-76** [comment]
Will check when I get home

Sent from Sky Yahoo Mail on Android 
 
  On Wed, 30 Oct 2024 at 5:48, ***@***.***> wrote:   


I confirm for my part as well. Works now, no more white screen. Thanks to the DEV.
Intel(R) Core(TM) i7-6700HQ / GeForce GTX 960
W10-64b 22H2

**Comment by Ennahh-76** [comment]
i can confirm that this is now working.  Thank You

**Comment by EmiMidnight** [comment]
Okay, closing this then. :)

**Comment by romadu** [comment]
The white screen issue has been resolved. However I cannot see bullets in attract mode or in-game.
