### ISSUE TITLE
Big Buck World multiplayer crashes 

### ISSUE THREAD

**Issue by cor094** [teknogods/TeknoParrotUI#850]
Tested latest TP version at time of opening this ticket. TPUI 1.0.0.1351, elfldr2 1.0.0.759. Previous crash fixes work beautifully for single player mode. Multiplayer modes (both traditional alternating gameplay AND simultaneous Big Buck Shootout mode) behave like single player did prior to crash fixes (i.e. jumbled leaderboard text followed by crash). I think it happens everywhere, but in case it matters, I was using P2 gun, Open Season part of the game, and Whitetail Deer adventure.

**Comment by cor094** [comment]
> I see this as well on Outback mode and any animal. Any players other than single player presents a crash normally when changing to the second player and shows the garbled text on screen then closes. If there is a way to enable logging to send in I’m open to reproducing the problem and providing the data.

Are you up to date on Teknoparrot? When I tested, the crashing was fixed, along with the garbled test. The only issue that remains that I've noticed is the 2 player score board  player column is incorrect, it's missing player names and shows bucks/scores instead.

**Comment by johnz1** [comment]
Multiplayer doesn't crash, but the scoreboard is totally messed up.  I created a new issue for that: https://github.com/teknogods/TeknoParrotUI/issues/888

**Comment by johnz1** [comment]
I think this can be closed.  I think it was fixed by this ElfLoader2.0 change on 8/31:
"Big Buck World: leaderboards, scores and all gibberish fixes"

**Comment by Poliwrath** [comment]
Thank you
