### ISSUE TITLE
Reaver deleting issues are we in regards to your conduct lying I have the screenshots

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [teknogods/TeknoParrotUI#853]
You blatantly lied on youtube making false allegations about me which is against E.U law in regards to me calling people a 'retard' now you have your deal take it or leave it and also it is now in the hands of youtube 
![image](https://github.com/user-attachments/assets/9253b6cf-1390-4147-ada9-8ce59750ff73)

Contact me via discord if you wish to chat about this or face the law!

**Comment by LordsOfTheRealm** [comment]
dude...go fuck yourself...you ome in the channel like your shit don't stink...enjoy our bans...freak....

**Comment by TheKitBoi** [comment]
> Contact me via discord if you wish to chat about this or face the law!

I'll contact on where you live

**Comment by LordsOfTheRealm** [comment]
yep...this person is nothing but want to be trouble..he's hurt because he can't et his way...poor freak....

**Comment by AngryScotsmanGaming** [comment]
You will not you will do as instructed or face the law and if you come near my channel on twitch or any platform I will be reporting you for harassment!

**Comment by AngryScotsmanGaming** [comment]
> You will not you will do as instructed or face the law and if you come near my channel on twitch or any platform I will be reporting you for harassment!

Go ask revear to show proof I actually used that word at anytime I'll wait for your response!

**Comment by TheKitBoi** [comment]
is this a social experiment

**Comment by LordsOfTheRealm** [comment]
> is this a social experiment

Winks...)

**Comment by Poliwrath** [comment]
Hi, please don't interact or engage with the github spam, it just creates more email and discord spam, thank you
