### ISSUE TITLE
Crazy but true! BG4 Tuned 2 player FFB

### ISSUE THREAD

**Issue by Riddler1** [teknogods/TeknoParrotUI#870]
I discovered this yesterday. First time trying 2 player LAN Race/Battle so i do not know how long this has been happening.

Player 2 wheel gets all of Player 1 Force Feedback!

Player 1 wheel does not get Player 2 FFB.
Player 1 FFB works normally
When Player 1 crashes/bumps wall, Player 2 wheel jerks and reacts.

When not playing a LAN game Race/Battle, both PC's FFB works normally. 

Player 1 wheel = Logitech G920
Player 2 wheel = Logitech G25

Service Mode:
Game ver. 2.08 JPN-P
Network Nesys = off 
Player 1 machine No. = 1
Player 2 machine No. = 2
Coin = Freeplay
Continue = off
Vendor Test = Key price 5 coins 

Teknoparrot settings:
Input API = Direct Input
TP Version 1.0.0.1320 ---> 1.0.0.1387
Professional mode = on
Enable all tracks = on
Hold Gear = on
Intro Fix = on
Network Broadcast addr: 192.168.0.255
Plyer1 PC ip = 192.168.1.1
Plyer2 PC ip = 192.168.1.2

Boomslang FFB plugin versions tested:
v2.0.0.52
v2.0.0.53

Troubleshooting:
1)reset ghost data in service mode
2)reset ranking data in service mode
3)deleted gst and rnk files from
C:user/appdata/local/VirtualStore folder
4)reverted plyr 2 FFB plugin to v2.0.0.37
5)DISCOVERY...In service mode i set Plyr 1 
    Machine No to "2" and then set Plyr 2 
    Machine No to "1". Now the opposite 
    happens... Plyr 1 PC gets all of Plyr 2 FFB!
6)turned off professional mode
7)updated TP version to 1.0.0.1387
8)updated FFB plugin to 2.0.0.52
9)reverted FFB plugin to 2.0.0.17

**Comment by LordsOfTheRealm** [comment]
you need to goto the discord in the FFBplugin help....this is not a github issue....

**Comment by Riddler1** [comment]
Thank you i will send to ffb boomslang for advice
