### ISSUE TITLE
Steering Input Issue

### ISSUE THREAD

**Issue by blisstik** [teknogods/TeknoParrotUI#883]
The latest version with a ton of commits and freeing MKDX 1.18 is causing steering issue, at least on Xinput. It affects MKDX and OutRun SP DX. Not sure if it affects others as well.

It seems that there is a reset of the input happening almost instanly.

**Comment by EmiMidnight** [comment]
Please update TPUI again, it should start to work again afterwards, sorry

**Comment by blisstik** [comment]
Fixed TY
