### ISSUE TITLE
[Minor issue] Sonic & Sega All Star Racing : introduction sound on the start of the race is interupted.

### ISSUE THREAD

**Issue by nixxou** [teknogods/TeknoParrotUI#895]
Minor issue is an understatement, but if no one report stuff, i guess it wont be fixed.

So, in Sonic & Sega All Star Racing, when you start a race, the audio of introduction announcement is cut.
See there : https://www.youtube.com/watch?v=fDpbMxQhlds

Interesting enough, an other launcher that i shall not name here got on one of their release patch note : "Sonic & Sega All Stars Racing, fixed introduction", so i guess that's something fixable one way or the other.

**Comment by Boomslangnz** [comment]
can you show any video where it shows this working as you say? Every video ive found on youtube from real cabs reacts same as TP from what I can see

https://youtu.be/u4EVjKJ8efo?si=p3RMjL28lN2IMJmt&t=37

https://youtu.be/tHMCmYrmby0?si=tiBzEi6w5fgLJT_8&t=88

**Comment by Boomslangnz** [comment]
pushed fix for this
