### ISSUE TITLE
BudgieLoader dont follow the gpu selection in windows preference

### ISSUE THREAD

**Issue by nixxou** [teknogods/TeknoParrotUI#904]
![image](https://github.com/user-attachments/assets/a5fe32c0-1be6-4932-8568-355dc6d02274)

This is kinda annoying because it's sometime an easy fix if you got a secondary gpu or a egpu to fix an amd related incompatibility.
I found a way to force elfloader to use a specific gpu, but it's not optimal, for that you need to make a monitor managed by the other cpu as primary, launch the game as windowed and move back the game window to your usual monitor.

**Comment by EmiMidnight** [comment]
This is not a budgieloader issue and is not something we can fix. Ask microsoft or the gpu driver teams. The best we could do is tell it to prefer high performance GPUs but not specifically which one.
