### ISSUE TITLE
Crimzon Clover - Crashing at launch after updating to latest build.

### ISSUE THREAD

**Issue by xudbux** [teknogods/TeknoParrotUI#922]
Crashing at launch after updating to latest build. most recent build back-up i have is teknoparrot 1.0.0.2530 where it still works

**Comment by nixxou** [comment]
I confirm the issue

**Comment by EmiMidnight** [comment]
Should be fixed with the next update out in a few minutes.

**Comment by xudbux** [comment]
tested with new update and is launching for me! thank you!
