### ISSUE TITLE
Re-Volt Arcade Issues

### ISSUE THREAD

**Issue by Santiii733** [teknogods/TeknoParrotUI#937]
Hey! About Re-Volt needs an option to enable as default arcade laps, because some ones if you put more laps = no more checkpoints (Using TeknoUI 1.0.0.1438). The original arcade uses random laps as default https://www.youtube.com/watch?v=a65z_iY4Xk4

Or what i need for set that?

**Comment by Santiii733** [comment]
Also needs add again Main Cabinet (The default Cabinet for default colors variant) + maybe a support for play online or use Network connect for be playable to 4 players

**Comment by Hydreigon223** [comment]
> Network connect for be playable to 4 players

The flyer states 8 player network connect but idk if test mode settings state otherwise. A manual hasn't been archived either.

**Comment by cor094** [comment]
I no longer have version prior to TP forcing laps to test, I just remember the first track had 5. Test menu has cab 1-8.  Default color is linked to cab ID and works well on my end.1 is red, 2 is blue, etc.

**Comment by Santiii733** [comment]
Old teknoParrot UI worked that with the original laps

**Comment by Santiii733** [comment]
> I no longer have version prior to TP forcing laps to test, I just remember the first track had 5. If each track was different it would be cool to have a custom lap check box that you could uncheck for default.Test menu has cab 1-8. Default color is linked to cab ID and works well on my end.1 is red, 2 is blue, etc. TP but supports 1-4 though, which is plenty for me. They connect over LAN for me. I'll post some tips in the TP lan channel soon

Default color is worked on TP old version, but on the lastest one can't use the original color car. Only the ID one's

**Comment by cor094** [comment]
> Toytanic 5 laps Suburbs 8 Laps Toy World 5 laps Supermarket 6 laps Garden 5 laps The Wrecking 5 laps Toy World 4 laps Museum 4 laps Nhood 3 laps Venice 4 laps
> 
> This ones is the correct laps in each circuit, but if you put 1 lap more or 2 in all tracks, when you finish the lap that was to where they originally made this map, the checkpoints cease to exist.

Dug around a bit in the game files, if you search game files for checkpoints.txt, there's an entry for number of laps in each of these files. I believe increasing the number of laps in these files would solve the issue of running out of checkpoints.

**Comment by Santiii733** [comment]
> > Toytanic 5 laps Suburbs 8 Laps Toy World 5 laps Supermarket 6 laps Garden 5 laps The Wrecking 5 laps Toy World 4 laps Museum 4 laps Nhood 3 laps Venice 4 laps
> > This ones is the correct laps in each circuit, but if you put 1 lap more or 2 in all tracks, when you finish the lap that was to where they originally made this map, the checkpoints cease to exist.
> 
> Dug around a bit in the game files, if you search game files for checkpoints.txt, there's several of them, and they have a line for number of laps in each of these files. I believe increasing the number of laps in these files would solve the issue of running out of checkpoints.

That worked thx! But idk why crashes in ending laps in museum 2 or nhood or maybe ending song crashes the game?

**Comment by cor094** [comment]
> > > Toytanic 5 laps Suburbs 8 Laps Toy World 5 laps Supermarket 6 laps Garden 5 laps The Wrecking 5 laps Toy World 4 laps Museum 4 laps Nhood 3 laps Venice 4 laps
> > > This ones is the correct laps in each circuit, but if you put 1 lap more or 2 in all tracks, when you finish the lap that was to where they originally made this map, the checkpoints cease to exist.
> > 
> > 
> > Dug around a bit in the game files, if you search game files for checkpoints.txt, there's several of them, and they have a line for number of laps in each of these files. I believe increasing the number of laps in these files would solve the issue of running out of checkpoints.
> 
> That worked thx! But idk why crashes in ending laps in museum 2 or nhood or maybe ending song crashes the game?
> 
> For the laps system, needs re-write the laps into the txt too
> 
> Yes, can confirm is crashing the game when the song ends

Glad that worked. Only crashes I've seen like that are related to using bad mss32.dll file (331kb) instead of clean one (320kb)

**Comment by Santiii733** [comment]
> > > > Toytanic 5 laps Suburbs 8 Laps Toy World 5 laps Supermarket 6 laps Garden 5 laps The Wrecking 5 laps Toy World 4 laps Museum 4 laps Nhood 3 laps Venice 4 laps
> > > > This ones is the correct laps in each circuit, but if you put 1 lap more or 2 in all tracks, when you finish the lap that was to where they originally made this map, the checkpoints cease to exist.
> > > 
> > > 
> > > Dug around a bit in the game files, if you search game files for checkpoints.txt, there's several of them, and they have a line for number of laps in each of these files. I believe increasing the number of laps in these files would solve the issue of running out of checkpoints.
> > 
> > 
> > That worked thx! But idk why crashes in ending laps in museum 2 or nhood or maybe ending song crashes the game?
> > For the laps system, needs re-write the laps into the txt too
> > Yes, can confirm is crashing the game when the song ends
> 
> Glad that worked. Only crashes I've seen like that are related to using bad mss32.dll file (331kb) instead of clean one (320kb)

Sometimes with clean mss32.dll crashes randomly in museum track

**Comment by cor094** [comment]
Not sure then. I ended up setting laps to 3 in TP. But, if playing a track that would normally have more than 3, the finish line says "checkpoint" instead of "finish". So I ended up setting laps to 3 in all my checkpoints.txt files to fix.

**Comment by Santiii733** [comment]
Lastest version of TP UI keeping crashing the game when the music ends, happens with original mss32.dll and modded one

**Comment by Santiii733** [comment]
Other thing, lastest UI version is glitched only RC Bandit car

**Comment by Santiii733** [comment]
> Other thing, lastest UI version is glitched only RC Bandit car
> 
> ![image](https://private-user-images.githubusercontent.com/16659154/376519671-6148b2b6-8255-4391-ba03-c13c3b418ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjUwMjAsIm5iZiI6MTcyOTA2NDcyMCwicGF0aCI6Ii8xNjY1OTE1NC8zNzY1MTk2NzEtNjE0OGIyYjYtODI1NS00MzkxLWJhMDMtYzEzYzNiNDE4Y2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3NDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1N2IyZWM3NzBiMWU5M2MwMDMzYWRiYzUzZjVhMTc3ODRjM2JlMWNiNzZjODA1NTA3OWJjNzEyMDlkMzkyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OdHVakDav-Cw28t3BmeF4gUkj-EFg479Wpfbd1RA8-k)

Update of this, only reproduces this glitch when the Windowed or CustomResolution is not enabled, about mss32.dll is fixed from a clean game path

**Comment by Santiii733** [comment]
Update, sent this video about this strange glitch

[https://www.youtube.com/watch?v=60h_a8WuEJU](url)

**Comment by Santiii733** [comment]
> Setting revolt.exe to Windows 98 compatibility mode fixed this glitch on my end.

Thx, this method worked
