### ISSUE TITLE
Battle Gear 4 : Input Mapping issue for Gaz and Brake

### ISSUE THREAD

**Issue by nixxou** [teknogods/TeknoParrotUI#958]
In Battle gear 4 (the non-tuned version), gaz and brake are inverted.
I saw that long time ago, but forget to raise an issue, i know it's minor, but it shouldn't take long to fix.

**Comment by nixxou** [comment]
I've made a demo of this issue here : https://youtu.be/uC42dmZ4js8

**Comment by EmiMidnight** [comment]
If I recall, this can happen if you calibrate the pedals ingame wrong, for some reason it inverts it if you do the calibration the wrong way around. Try deleting the games config file so it asks you to recalibrate on boot and check if that helps.

**Comment by nixxou** [comment]
@EmiMidnight Ok, thanks. I confirm that test menu and recalibration solved the issue.
