### ISSUE TITLE
5 questions of a tp subscriber

### ISSUE THREAD

**Issue by Haile1983** [teknogods/TeknoParrotUI#965]
As a tp subscriber my post got deleted very fast without answers so i’m asking again:
1.when will you guys start working on elfldr2 64 bit to enable halo arcade support?
2.when will terminal emu for exvs2+xboost be added for users with one pc without a vpn?
3.wangan 6 server is still offline for a very long time will it EVER be back as promised?
4.does fate of grand order still worked on? as you probably know version 10.80 is public
5.what's the point of adding gunslinger 3 to the tpui if its not playable?

**Comment by nzgamer41** [comment]
Take your schizo meds
