### ISSUE TITLE
Raccoon Rampage Direct aim mode locks up gun

### ISSUE THREAD

**Issue by magicray1028** [teknogods/TeknoParrotUI#979]
direct aim mode locks the gun4IR recoil and locks the cursor to center of screen. possibly needs com port blocking?

**Comment by PolybiusExtreme** [comment]
I have the same problem

**Comment by EmiMidnight** [comment]
Are you sure this is specifically the direct aim mode and not the game in general? Because all it does is skip the calibration code, no com port, no mouse movement or anything.

**Comment by PolybiusExtreme** [comment]
@EmiMidnight I have the issue also with direct aim disabled

**Comment by magicray1028** [comment]
same , enabled or disabled, using gun4ir causes it to be stuck and recoil failing to work.

**Comment by EmiMidnight** [comment]
How does Gun4IR work? I don't see any serial port attempts in my logs, for what it's worth.

**Comment by PolybiusExtreme** [comment]
@EmiMidnight It works like a normal mouse. If the mouse cursor hangs in the middle of the screen, only a full shutdown of the pc brings the normal function of the mouse cursor back.

**Comment by EmiMidnight** [comment]
Well if it worked just like a normal mouse, then the cursor wouldn't get locked. And normal mice don't have recoil either.

**Comment by PolybiusExtreme** [comment]
![IMG_1597](https://github.com/user-attachments/assets/a8378aef-80f2-4374-ba99-fba4f7328e84)
The recoil works via com ports.
The GUN4IR is USB Composite Device in USBDeview. Not an USB Input Device (HID) like a mouse.

**Comment by EmiMidnight** [comment]
Pushing an update but I am not very hopeful it will help. Still, it's worth a try. Please let me know how it goes if any of you try it. Should be out in a few minutes.

**Comment by EmiMidnight** [comment]
Coolio, closing this then
