### ISSUE TITLE
7 suggestions 

### ISSUE THREAD

**Issue by Haile1969** [teknogods/TeknoParrotUI#988]
Reaver here are 7 suggestions how to improve users
experience/service/communication with/of tp:
1.remove the unnecessary bot and manual verification and allow everyone to join tp discord freely as before simply try to be open minded and see for yourself 
2.answer questions of users about fixes or more games support even if you don’t have answers you can at least say thank you for mentioning it we will check it instead of ban/mute/ignore them
3.some users got a nerve to tell others what they can ask tp devs or not
and you allow that despite you know that any tp subscriber can ask for more games support/fixes whenever he likes
4.don’t expect the community to fix issues for you as you suggested like the recent sound issues of king of the road,lets go jungle etc you guys getting paid to do it not others 
5.make a new specific channel on discord so people can ask for future games to be supported by tp and answered by a dev
6.restrain nibs he ban/mute users for asking questions about games support or fixes
and even made users timed out automatically just to prevent them from asking that’s not being strict as you described him before that’s overmoderate making users stop using tp 
7.the way to reach 3000 subscribers and above is to work on public games available 
and there are many as you know that still not supported by tp you got a nice income 
so why not hire at least another dev to reduce the workload from pocky/coffee?
reaver simply lower your big ego a bit and start listening more to users 
people that ain’t worship you like some do regularly ain’t haters 
good evening

**Comment by AngryScotsmanGaming** [comment]
Bud it will fall on deaf ears the guy goes around making false accusations about people i.e me then admits he lied on their on streams on youtube, he has yet to unban me and apologise after all the hate I received on their discord, it's full of simps and tekno parrot can do no wrong and the discord is a cesspit of losers who can say and do as they please!

Even Github care not for their actions and the issue will shortly be closed as you cannot speak out against them!

**Comment by LordsOfTheRealm** [comment]
wow 2 phychos in 1....amazing....

**Comment by AngryScotsmanGaming** [comment]
> wow 2 phychos in 1....amazing....

My point exactly right here are you a dog???? if not get your tongue out of reavers ass please!
